### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by IhleMa** [TheLiteCrafter/AsepriteTool#3]
I get an error message from ninja when installing.

`FAILED: third_party/json11/CMakeFiles/json11.dir/json11.cpp.obj
C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DNDEBUG -DPNG_NO_MMX_CODE -D_CRT_SECURE_NO_WARNINGS -IC:\aseprite\third_party\zlib -IC:\aseprite\build\third_party\zlib -IC:\aseprite\third_party\libpng -IC:\aseprite\build\third_party\libpng -IC:\aseprite\third_party\libwebp\src -IC:\aseprite\third_party\tinyxml -IC:\aseprite\third_party\pixman\pixman -IC:\aseprite\build -IC:\aseprite\third_party\giflib -IC:\aseprite\third_party\jpeg -IC:\aseprite\third_party\curl\include -IC:\aseprite\third_party\simpleini -IC:\aseprite\third_party\. -IC:\aseprite\third_party\json11 /DWIN32 /D_WINDOWS /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG -MT -fPIC -fno-rtti -fno-exceptions -Wall /showIncludes /Fothird_party\json11\CMakeFiles\json11.dir\json11.cpp.obj /Fdthird_party\json11\CMakeFiles\json11.dir\json11.pdb /FS -c C:\aseprite\third_party\json11\json11.cpp
cl : Befehlszeile warning D9002 : Unbekannte Option "-fPIC" wird ignoriert.
cl : Befehlszeile warning D9002 : Unbekannte Option "-fno-rtti" wird ignoriert.
cl : Befehlszeile warning D9002 : Unbekannte Option "-fno-exceptions" wird ignoriert.
C:\aseprite\third_party\json11\json11.cpp(171): warning C4626: "json11::Value<json11::Json::NUMBER,double>": Der Zuweisungsoperator wurde implizit als gelöscht definiert.
C:\aseprite\third_party\json11\json11.cpp(173): note: Siehe Verweis auf die gerade kompilierte Klasse Vorlage-Instanziierung "json11::Value<json11::Json::NUMBER,double>".
C:\aseprite\third_party\json11\json11.cpp(171): warning C5027: "json11::Value<json11::Json::NUMBER,double>": Der Operator zum Verschieben einer Zuweisung wurde implizit als gelöscht definiert.
C:\aseprite\third_party\json11\json11.cpp(180): warning C4626: "json11::JsonDouble": Der Zuweisungsoperator wurde implizit als gelöscht definiert.
C:\aseprite\third_party\json11\json11.cpp(180): warning C5027: "json11::JsonDouble": Der Operator zum Verschieben einer Zuweisung wurde implizit als gelöscht definiert.
INTERNER COMPILERFEHLER in "C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x64\cl.exe"
    Klicken Sie im Menü "Hilfe" von Visual C++ auf "Technischer Support",
    oder öffnen Sie die Hilfe zum technischen Support, um weitere Informationen zu erhalten.
[439/1531] Building C object third_party\libarchive\libarc...archive_static.dir\archive_read_support_filter_lrzip.c.obj
ninja: build stopped: subcommand failed.`

If you need the german translated, letme know.

**Comment by ananyatimalsina** [comment]
Deutsch sollte kein problem sein :) Der Fehler hat etwas mit vs zu tun aber bin mir nich sicher was genau. Du solltest nochmal einen clean install probieren (alles loeschen, inklusive C:/aseprite u. C:/deps, dann neu installieren.)

**Comment by vincentburkhardt** [comment]
Habe so gut wie das gleiche Problem.
Auch bei der manuellen [aseprite github repo Anleitung](https://github.com/aseprite/aseprite/blob/main/INSTALL.md) kommt die Fehlermeldung "ninja: build stopped: subcommand failed".

Ich habe unter anderen verschiedene VS Community Versionen (2019/2022) mit dem Windows 10 SDK ausprobiert, sowie Skia, CMake und ninja auf Kompatibiltät überprüft.

Ich schau mal unter den issues bei [aseprite ](https://github.com/aseprite/aseprite) vorbei, wenn ich was finde melde ich mich.

**Comment by innocentDE** [comment]
Okay, hab das Problem gefunden. 

So it turns out that I've chosen the wrong module in the Visual Studio Installer (not the Windows 10 SDK version, but the wrong C++ module). Somehow the compiler detects missing files/packages and does not completely compile. It was as simple as installing the right module (Desktop Development with C++ instead of Game Development) et voilà - no problem at all.

**Comment by vincentburkhardt** [comment]
Okay, I got it!

make sure you install vs community 2019 with the correct windows 10 sdk version
for some weird reason it can't compile with 2022

check the install.md in the aseprite folder, not the github page!
you have to use the right skia version in order to compile successfully
