### ISSUE TITLE
it didn't download "aseprite.exe"

### ISSUE THREAD

**Issue by LegendStormCloud** [TheLiteCrafter/AsepriteTool#5]

**Comment by ananyatimalsina** [comment]
Please provide additional information

**Comment by LegendStormCloud** [comment]
i did all of the requirement and installed all but when i try to open aseprite it say missing link and can't find aseprite.exe

**Comment by ananyatimalsina** [comment]
Take a look at the terminal and see which error it returns

**Comment by LegendStormCloud** [comment]
ok it worked
